spring:
  datasource:
    driver-class: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-aulo: update
    properties:
      hibernate:
        format_sql: true